using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using DeltaSync.Core.Chunking;
using FluentAssertions;
using Xunit;
using Xunit.Abstractions;

namespace DeltaSync.Tests.Chunking;

public class ChunkFingerprinterTests
{
    private readonly ITestOutputHelper _output;

    public ChunkFingerprinterTests(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    public void SpecSection10_Check1_ShiftInvarianceTest_RetainsOver95PercentIdenticalChunks()
    {
        // 1. Generate 5 MB pseudo-random byte payload
        int originalSize = 5 * 1024 * 1024;
        var originalData = new byte[originalSize];
        var rng = new Random(424242);
        rng.NextBytes(originalData);

        // 2. Prepend 100 random bytes
        int prependSize = 100;
        var prependBytes = new byte[prependSize];
        rng.NextBytes(prependBytes);

        var prependedData = new byte[originalSize + prependSize];
        Buffer.BlockCopy(prependBytes, 0, prependedData, 0, prependSize);
        Buffer.BlockCopy(originalData, 0, prependedData, prependSize, originalSize);

        // 3. Chunk and fingerprint both streams
        var manifestOriginal = ChunkFingerprinter.CreateManifest("large-dataset.bin", originalData);
        var manifestPrepended = ChunkFingerprinter.CreateManifest("large-dataset.bin", prependedData);

        manifestOriginal.Chunks.Should().NotBeEmpty();
        manifestPrepended.Chunks.Should().NotBeEmpty();

        // 4. Calculate chunk intersection
        var originalHashes = manifestOriginal.Chunks.Select(c => c.HashHex).ToHashSet(StringComparer.OrdinalIgnoreCase);
        int matchedChunkCount = manifestPrepended.Chunks.Count(c => originalHashes.Contains(c.HashHex));
        double matchRatio = (double)matchedChunkCount / manifestPrepended.Chunks.Count;
        double matchPercentage = matchRatio * 100.0;

        _output.WriteLine($"[Check 1] Original chunks: {manifestOriginal.Chunks.Count}, Prepended chunks: {manifestPrepended.Chunks.Count}");
        _output.WriteLine($"[Check 1] Matched chunks: {matchedChunkCount} / {manifestPrepended.Chunks.Count} ({matchPercentage:F2}%)");

        // Assert Spec §10 Check 1 requirement: >95% identical chunks retained
        matchRatio.Should().BeGreaterThan(0.95,
            $"FastCDC shift invariance must preserve >95% of chunks when 100 bytes are prepended to a 5MB payload (measured: {matchPercentage:F2}%)");

        // 5. Verify manifest differencing
        var diff = ChunkFingerprinter.ComputeDiff(manifestPrepended, manifestOriginal);
        diff.MatchedChunkCount.Should().Be(matchedChunkCount);
        diff.MissingChunkCount.Should().Be(manifestPrepended.Chunks.Count - matchedChunkCount);
        diff.ReuseRatio.Should().BeGreaterThan(0.95);

        // For a 100-byte prepend, only the boundary containing the prepend should differ (typically 1 chunk, <= 128KB)
        diff.MissingBytes.Should().BeLessThanOrEqualTo(256 * 1024,
            "Only the shifted head chunk should require retransmission");
        diff.MissingChunkCount.Should().BeInRange(1, 2);

        _output.WriteLine($"[Check 1] Delta Transfer: Reused {diff.ReusedBytes:N0} bytes ({diff.ReuseRatio * 100:F2}%), Transferred {diff.MissingBytes:N0} bytes across network");
    }

    [Fact]
    public void KnownAnswerVector_StandardVerificationString_ProducesDeterministicChunksAndHashes()
    {
        // Deterministic 1 MB test vector generated by repeating a fixed ASCII sequence
        string pattern = "DeltaSync-FastCDC-Verification-String-0123456789\n";
        byte[] patternBytes = Encoding.UTF8.GetBytes(pattern);
        int targetLength = 1024 * 1024; // 1 MB
        var buffer = new byte[targetLength];

        int written = 0;
        while (written < targetLength)
        {
            int toCopy = Math.Min(patternBytes.Length, targetLength - written);
            Buffer.BlockCopy(patternBytes, 0, buffer, written, toCopy);
            written += toCopy;
        }

        var manifest1 = ChunkFingerprinter.CreateManifest("known_vector.txt", buffer);
        var manifest2 = ChunkFingerprinter.CreateManifest("known_vector.txt", buffer);

        // Verification 1: Pure determinism
        manifest1.Should().Be(manifest2);
        manifest1.GetHashCode().Should().Be(manifest2.GetHashCode());

        // Verification 2: Verify chunk counts and structure
        manifest1.Chunks.Should().NotBeEmpty();
        manifest1.FileSize.Should().Be(targetLength);
        manifest1.RootHash.Should().HaveLength(64);

        long cumulative = 0;
        for (int i = 0; i < manifest1.Chunks.Count; i++)
        {
            var chunk = manifest1.Chunks[i];
            chunk.Index.Should().Be(i);
            chunk.Offset.Should().Be(cumulative);
            chunk.Hash.Should().HaveCount(32);
            chunk.HashHex.Should().HaveLength(64);

            cumulative += chunk.Length;
        }
        cumulative.Should().Be(targetLength);

        // Verification 3: Verify root hash matches raw SHA-256
        string expectedRoot = Convert.ToHexString(SHA256.HashData(buffer)).ToLowerInvariant();
        manifest1.RootHash.Should().Be(expectedRoot);

        _output.WriteLine($"[Known-Answer] Chunks: {manifest1.Chunks.Count}, RootHash: {manifest1.RootHash}");
    }

    [Fact]
    public void InPlaceEdit_5BytesModifiedIn1MB_RequiresOnlySingleChunkTransfer()
    {
        int size = 1024 * 1024;
        var original = new byte[size];
        var rng = new Random(1337);
        rng.NextBytes(original);

        var modified = (byte[])original.Clone();
        // Modify 5 bytes right around offset 500,000
        for (int i = 0; i < 5; i++)
        {
            modified[500_000 + i] = (byte)(modified[500_000 + i] ^ 0xFF);
        }

        var origManifest = ChunkFingerprinter.CreateManifest("doc.dat", original);
        var modManifest = ChunkFingerprinter.CreateManifest("doc.dat", modified);

        var diff = ChunkFingerprinter.ComputeDiff(modManifest, origManifest);

        // Only the single chunk containing the in-place edit should be missing
        diff.MissingChunkCount.Should().Be(1);
        diff.MatchedChunkCount.Should().Be(modManifest.Chunks.Count - 1);
        diff.MissingBytes.Should().BeLessThanOrEqualTo(FastCdcConfig.Default.MaxSize);
        diff.ReuseRatio.Should().BeGreaterThan(0.90);

        _output.WriteLine($"[In-Place Edit] Missing: {diff.MissingChunkCount} chunk ({diff.MissingBytes} bytes), Reused: {diff.ReusedBytes} bytes");
    }

    [Fact]
    public void EmptyBuffer_GeneratesEmptyManifestWithCanonicalEmptyRootHash()
    {
        var manifest = ChunkFingerprinter.CreateManifest("empty.txt", ReadOnlyMemory<byte>.Empty);

        manifest.FileSize.Should().Be(0);
        manifest.Chunks.Should().BeEmpty();
        manifest.RootHash.Should().Be(FileManifest.EmptyRootHash);
        manifest.RelativePath.Should().Be("empty.txt");

        var diff = ChunkFingerprinter.ComputeDiff(manifest, manifest);
        diff.IsIdentical.Should().BeTrue();
        diff.MissingChunkCount.Should().Be(0);
        diff.MissingBytes.Should().Be(0);
    }

    [Theory]
    [InlineData(1)]
    [InlineData(500)]
    [InlineData(16_383)]
    public void MicroBuffer_SmallerThanMinSize_GeneratesSingleChunkMatchingRootHash(int length)
    {
        var buffer = new byte[length];
        Array.Fill(buffer, (byte)0x7F);

        var manifest = ChunkFingerprinter.CreateManifest("small.bin", buffer);

        manifest.FileSize.Should().Be(length);
        manifest.Chunks.Should().HaveCount(1);
        manifest.Chunks[0].Index.Should().Be(0);
        manifest.Chunks[0].Offset.Should().Be(0);
        manifest.Chunks[0].Length.Should().Be(length);

        // In a single-chunk file, root hash equals chunk hash
        manifest.RootHash.Should().Be(manifest.Chunks[0].HashHex);
    }

    [Fact]
    public void StreamOverload_ProducesIdenticalManifestToMemoryOverload()
    {
        var buffer = new byte[250_000];
        Random.Shared.NextBytes(buffer);

        var fromMemory = ChunkFingerprinter.CreateManifest("test.bin", buffer);

        using var ms = new MemoryStream(buffer);
        var fromStream = ChunkFingerprinter.CreateManifest("test.bin", ms);

        fromStream.Should().Be(fromMemory);
    }

    [Fact]
    public void ManifestDiff_NullLocalManifest_ReportsAllChunksMissing()
    {
        var buffer = new byte[100_000];
        Random.Shared.NextBytes(buffer);

        var remoteManifest = ChunkFingerprinter.CreateManifest("remote.bin", buffer);

        var diff = ChunkFingerprinter.ComputeDiff(remoteManifest, localManifest: null);

        diff.MissingChunkCount.Should().Be(remoteManifest.Chunks.Count);
        diff.MissingBytes.Should().Be(remoteManifest.FileSize);
        diff.MatchedChunkCount.Should().Be(0);
        diff.ReusedBytes.Should().Be(0);
        diff.ReuseRatio.Should().Be(0.0);
        diff.IsIdentical.Should().BeFalse();
    }

    [Fact]
    public void ManifestDiff_IdenticalRootHashes_FastPathsToZeroMissing()
    {
        var buffer = new byte[100_000];
        Random.Shared.NextBytes(buffer);

        var manifestA = ChunkFingerprinter.CreateManifest("file.bin", buffer);
        var manifestB = ChunkFingerprinter.CreateManifest("other_path.bin", buffer);

        var diff = ChunkFingerprinter.ComputeDiff(manifestA, manifestB);

        diff.IsIdentical.Should().BeTrue();
        diff.MissingChunkCount.Should().Be(0);
        diff.MissingBytes.Should().Be(0);
        diff.MatchedChunkCount.Should().Be(manifestA.Chunks.Count);
        diff.ReusedBytes.Should().Be(manifestA.FileSize);
        diff.ReuseRatio.Should().Be(1.0);
    }

    [Fact]
    public void ManifestDiff_WithAvailableHashesSet_IdentifiesMissingCorrectly()
    {
        var buffer = new byte[300_000];
        Random.Shared.NextBytes(buffer);

        var manifest = ChunkFingerprinter.CreateManifest("file.bin", buffer);
        manifest.Chunks.Count.Should().BeGreaterThan(2);

        // Suppose local SQLite store only has chunk 0 and chunk 2
        var availableHashes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            manifest.Chunks[0].HashHex,
            manifest.Chunks[2].HashHex
        };

        var diff = ChunkFingerprinter.ComputeDiff(manifest, availableHashes);

        diff.MatchedChunkCount.Should().Be(2);
        diff.MatchedChunks.Select(c => c.Index).Should().Contain(new[] { 0, 2 });
        diff.MissingChunkIndices.Should().NotContain(0);
        diff.MissingChunkIndices.Should().NotContain(2);
        diff.MissingChunkIndices.Should().Contain(1);
    }

    [Fact]
    public void ChunkDescriptor_StructuralEqualityAndValidation()
    {
        byte[] hash1 = new byte[32];
        hash1[0] = 0xAA;
        byte[] hash2 = new byte[32];
        hash2[0] = 0xAA;
        byte[] hash3 = new byte[32];
        hash3[0] = 0xBB;

        var d1 = new ChunkDescriptor(0, 0, 1024, hash1);
        var d2 = new ChunkDescriptor(0, 0, 1024, hash2);
        var d3 = new ChunkDescriptor(0, 0, 1024, hash3);

        d1.Should().Be(d2);
        d1.GetHashCode().Should().Be(d2.GetHashCode());
        d1.Should().NotBe(d3);

        // Validation errors
        FluentActions.Invoking(() => new ChunkDescriptor(-1, 0, 1024, hash1))
            .Should().Throw<ArgumentOutOfRangeException>();
        FluentActions.Invoking(() => new ChunkDescriptor(0, -1, 1024, hash1))
            .Should().Throw<ArgumentOutOfRangeException>();
        FluentActions.Invoking(() => new ChunkDescriptor(0, 0, -1, hash1))
            .Should().Throw<ArgumentOutOfRangeException>();
        FluentActions.Invoking(() => new ChunkDescriptor(0, 0, 1024, null!))
            .Should().Throw<ArgumentNullException>();
        FluentActions.Invoking(() => new ChunkDescriptor(0, 0, 1024, new byte[16]))
            .Should().Throw<ArgumentException>();
    }

    [Fact]
    public void FileManifest_Validation_RejectsInvalidStructures()
    {
        byte[] hash = new byte[32];
        var chunk0 = new ChunkDescriptor(0, 0, 100, hash);
        var chunk1 = new ChunkDescriptor(1, 100, 200, hash);
        var validChunks = new[] { chunk0, chunk1 };
        string validRoot = Convert.ToHexString(new byte[32]).ToLowerInvariant();

        // Null / whitespace path
        FluentActions.Invoking(() => new FileManifest("", 300, validRoot, validChunks))
            .Should().Throw<ArgumentException>();

        // Negative size
        FluentActions.Invoking(() => new FileManifest("doc.txt", -1, validRoot, validChunks))
            .Should().Throw<ArgumentOutOfRangeException>();

        // Invalid root hash format
        FluentActions.Invoking(() => new FileManifest("doc.txt", 300, "short-hash", validChunks))
            .Should().Throw<ArgumentException>();

        // Non-monotonic indices
        var badIndexChunks = new[] { chunk1, chunk0 };
        FluentActions.Invoking(() => new FileManifest("doc.txt", 300, validRoot, badIndexChunks))
            .Should().Throw<ArgumentException>();

        // Non-contiguous offsets
        var gapChunk1 = new ChunkDescriptor(1, 150, 150, hash);
        FluentActions.Invoking(() => new FileManifest("doc.txt", 300, validRoot, new[] { chunk0, gapChunk1 }))
            .Should().Throw<ArgumentException>();

        // Size mismatch
        FluentActions.Invoking(() => new FileManifest("doc.txt", 999, validRoot, validChunks))
            .Should().Throw<ArgumentException>();
    }
}
